# Generated by Django 5.1.3 on 2024-12-07 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.menuitem'),
        ),
    ]
