# Generated by Django 5.1.3 on 2024-12-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_bill_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
    ]
